5pm-3 TP Added code so that the Home page and Basic Search page now shows Fall 2008 to Fall 2021 instead of a hard coded list of 3 quarters
ucsb-cs156-s21/proj-ucsb-courses-search pull request #281
Opened 2021-05-16 06:19 UTC by thaophan1

## Main Changes
Added quarterRange function and SelectQuarter component to create a new form that shows an expandable list of quarters in the given range.
The list of quarters is generated by the quarterRange function with startQuarter and endQuarter input
The QuarterSelector form is generated by SelectQuarter component given {quarters, quarter, setQuarter, controlId, label} props.

## Files Changed
javascript/src/main/components/BasicCourseSearch/BasicCourseSearchForm.js
javascript/src/main/components/BasicCourseSearch/CourseSearchFormQtrDeptOnly.js

2021-05-17 20:22 UTC, squirmel submitted a review, later dismissed
LGTM

2021-05-17 20:23 UTC, chucklesbao submitted a review, later dismissed
LGTM

2021-05-18 23:55 UTC, pconrad approved these changes
LGTM... pending a test on the deployment at  https://proj-ucsb-courses-search-qa.herokuapp.com

If it looks ok there, I'll merge it.  Stand by...

2021-05-18 23:55 UTC, pconrad commented on javascript/src/main/components/BasicCourseSearch/CourseSearchFormQtrDeptOnly.js
> +					<option>MATH</option>
This isn't a blocker for this particular PR.  But I'd suggest, if there isn't already a story for this, making a story to replace this hard coded list with a usage of the `SelectSubject` component.

But, again, that's for another story (and that story may already exist?)

2021-05-19 00:06 UTC, pconrad requested changes
Please change these two instances of 20214 to 20213.

2021-05-19 00:06 UTC, pconrad commented on javascript/src/main/components/BasicCourseSearch/BasicCourseSearchForm.js
> +	const quarters = quarterRange("20084", "20214");
Since there is a bug with 20214 data, lets change this to:

```
quarterRange("20084", "20213");
```

2021-05-19 00:06 UTC, pconrad commented on javascript/src/main/components/BasicCourseSearch/CourseSearchFormQtrDeptOnly.js
> +	const quarters = quarterRange("20084", "20214");
Since there is a bug with 20214 data, lets change this to:

```
quarterRange("20084", "20213");
```

2021-05-19 00:38 UTC, pconrad approved these changes

2021-05-19 00:39 UTC, squirmel approved these changes
LGTM

2021-05-19 00:39 UTC, chucklesbao approved these changes
Love the hard work changing that 4 to a 3! LOOKS GOOD TO ME!!!

2021-05-19 00:41 UTC, mknguyen1202 approved these changes
Good hard work! LGTM!

2021-05-19 00:46 UTC, merged